version: '3.8'

services:
  app:
    build: .
    container_name: veyra_backend_app
    restart: always
    ports:
      - "${APP_PORT:-8080}:8080"
    # Ya no dependemos de servicios locales, Spring Boot se conectará directamente a Atlas/Aiven
    environment:
      - SPRING_PROFILES_ACTIVE=prod

      # Base de Datos Relacional (Aiven MySQL)
      # Ahora estas variables deben contener la URL pública, puerto y credenciales que te da Aiven
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

      # MongoDB (MongoAtlas URI completa)
      # Esta variable contendrá el string "mongodb+srv://..." que te da Atlas
      - MONGODB_URI=${MONGODB_URI}

      # Seguridad JWT
      - AUTHORIZATION_JWT_SECRET=${AUTHORIZATION_JWT_SECRET}
      - AUTHORIZATION_JWT_EXPIRATION_DAYS=${AUTHORIZATION_JWT_EXPIRATION_DAYS}

      # Pasarela de Pagos (Stripe)
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}

      # Almacenamiento (Cloudinary)
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"