environment.name=dev
## Spring Application Name
spring.datasource.url=jdbc:mysql://localhost:3306/veyra?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678

## MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/veyra
spring.data.mongodb.database=veyra
# Stripe Configuration Properties
stripe.api.key=STRIPE_API_KEY
stripe.webhook.secret=STRIPE_WEBHOOK_SECRET

# Cloudinary Configuration Properties
cloudinary.cloud-name=duwo1mnfk
cloudinary.api-key=726963324388622
cloudinary.api-secret=fspAT6V7wiZ4L_fwbDO8qRHNBJA
spring.jpa.show-sql=true


# JWT Configuration Properties
authorization.jwt.secret = WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days = 7